spring:
  profiles:
    default: dev
    active: ${SPRING_PROFILE:dev}
  application:
    name: contact-manager-spring-boot
  jpa:
    hibernate:
      ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true		
logging:
  level: 
    ua.com.javarush.gnew.contactm: DEBUG
    org.springframework.security: DEBUG

cloudinary:
  name: dru4hznjk
  api-key: 374119777715921
  api-secret: 9OfudXe_H4kM7o5NmwdDRXW8yuQ