jwt:
  secret: T9MBTpP38oYV2r6BgMvSE09MsFCGiJ5bEagLAWmMmsCusw5euyck4qmyIcn5XgP6
  expiration: 3600000
server:
  error:
    whitelabel:
      enabled: false # disable the Whitelabel page
    include-message: always # always include the HTTP message

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate


logging:
  level:
    root: info
  file:
    name: logs/app.log