server:
  error:
    whitelabel:
      enabled : false # disable the Whitelabel page
    include-message: always # always include the HTTP message

spring:
  jpa:
    hibernate:
      ddl-auto: update