### Get a contact by id
GET {{host}}/{{api.path}}/{{api.version}}/contact?id=1


### Create a contact
POST {{host}}/{{api.path}}/{{api.version}}/contact
Content-Type: application/json

{
  "name": "John Doe",
  "emails": [
    {"email": "john.doe2@example.com"},
    {"email": "j2.doe@example.org"}
  ],
  "phones": [
    {"phone": "+12345678902"},
    {"phone": "+09876543212"}
  ],
  "networks": [
    {"label": "github", "account": "johnGithub2"}
  ]
}

### Update a contact
PUT {{host}}/{{api.path}}/{{api.version}}/contact?id=2
Content-Type: application/json

{
  "name": "John Doe Updated",
  "emails": [
    {"email": "john.updated@example.com"}
  ],
  "phones": [
    {"phone": "+11111111111"}
  ],
  "networks": [
    {"label": "linkedin", "account": "johnLinkedIn"}
  ]
}

### Delete a contact
DELETE {{host}}/{{api.path}}/{{api.version}}/contact?id=2