### Get a contact book by id
GET {{host}}/{{api.path}}/{{api.version}}/contact-book?id=1


### Create a contact book
POST {{host}}/{{api.path}}/{{api.version}}/contact-book
Content-Type: application/json

{
  "name": "My contacts",
  "contacts": [
    {
      "name": "Alice",
      "lastName": "Smith",
      "emails": [
        {"email": "alice@example.com"}
      ],
      "phones": [
        {"phone": "+380501112233"}
      ],
      "networks": [
        {"label": "telegram", "account": "@alice_ua"}
      ]
    },
    {
      "name": "Bob Johnson",
      "emails": [
        {"email": "bob@example.com"}
      ],
      "phones": [
        {"phone": "+380671234567"}
      ],
      "networks": [
        {"label": "facebook", "account": "bob.j"}
      ]
    }
  ]
}

### Update a contact book
PUT {{host}}/{{api.path}}/{{api.version}}/contact-book?id=1
Content-Type: application/json

{
  "name": "Updated Contacts",
  "contacts": [
    {
      "name": "Charlie",
      "lastName": "Updated",
      "emails": [
        {"email": "charlie@example.com"}
      ],
      "phones": [
        {"phone": "+12312312312"}
      ],
      "networks": [
        {"label": "twitter", "account": "charlie_tw"}
      ]
    }
  ]
}

### Delete a contact book
DELETE {{host}}/{{api.path}}/{{api.version}}/contact-book?id=1
